---
# tasks file for install_docker
- name: Update the apt package and install packages to allow apt to use a repository over HTTPS
  apt: 
    update_cache: yes
    name: 
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Create the keyring directory if not exist
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add docker's GPG key to the keyrings directory
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'

- name: Add docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    update_cache: true

- name: Install docker 
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Add current user to the docker group
  user: 
    name: ubuntu
    groups: docker
    append: yes
